name = "TSConditioning"
uuid = "65444e21-13b1-5fbd-b269-b51e5fd998ef"
authors = ["Galen Lynch <galen@galenlynch.com>"]
version = "0.1.3"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
GLUtilities = "8b4c6747-1f02-570a-a961-a96037df41d6"
JoinedArrays = "34c7ed6b-ff08-5868-b4e9-6a77a2b436e9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DSP = "0.5 - 0.7"
GLUtilities = "0.0.5 - 0.2"
JoinedArrays = "0.0.2 - 0.1"
MultivariateStats = "0.6 - 0.7"
julia = "1.6"
