name = "TSConditioning"
uuid = "65444e21-13b1-5fbd-b269-b51e5fd998ef"
authors = ["Galen Lynch <galen@galenlynch.com>"]
version = "0.1.4"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
JoinedArrays = "34c7ed6b-ff08-5868-b4e9-6a77a2b436e9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
SignalIndices = "18f53e89-494d-4131-905c-653e8ada6cd8"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DSP = "0.8"
JoinedArrays = "0.0.2 - 0.1"
MultivariateStats = "0.6 - 0.10"
SignalIndices = "0.1.1"
julia = "1.10"
