name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Install CompatHelper
        run: using Pkg; Pkg.add("CompatHelper")
        shell: julia --color=yes {0}
      - name: Add custom registry
        run: using Pkg; Pkg.Registry.add(Pkg.RegistrySpec(url="https://github.com/galenlynch/GalenRegistry.git"))
        shell: julia --color=yes {0}
      - name: Run CompatHelper
        run: using CompatHelper; CompatHelper.main(; use_existing_registries=true)
        shell: julia --color=yes {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
